### ISSUE TITLE
#16 part 2

### ISSUE THREAD

**Issue by PF94** [JarTeam/retrosite#19]
Cannot reopen #16 so...

I made fixes on Retrosite, but Jarhead reverted all of those changes, readding the fucking bloat that I removed to conserve file storage.

YOU DO FUCKING REALIZE THAT THE RETROSITE FOLDER ONCE GIT CLONED TAKES A FUCKING GIGABYTE OF STORAGE BECAUSE THE .GIT FOLDER STILL REMEMBERS THE FUCKING BLOAT

YOU FUCKING REVERTED THE FIX I MADE TO STALKER HISTORIAS'S SUBSITE, SO NOW IT'S FUCKING UNLISTED YET AGAIN, YOU REVERTED THE 2003PAGE BUTTON SO NOW IT SHOWS THE OLD OUTDATED BUTTON, AND IT FUCKING LINKS TO 2003PAGE FOREVER, WHICH MENTIONS "most importently the whole website was closed." WHICH IS COMPLETELY FUCKING OUTDATED AND IS MISINFOMATION.

I GET IT, YOU GUYS HAVE NO QUALITY CONTROL AND YOU ALLOW 300+ MB OF POSSIBLY COPYRIGHTED AUDIO SITTING ON A SOURCE CODE OF A FUCKING WEBSITE INSTEAD OF PUTTING THOSE FUCKING FILES ON MEGA.

RETROSITE ONLY EXISTS BECAUSE 2003PAGE FUCKING GOT REDESIGNED THAT ONE TIME, RETROSITE HAS NO PURPOSE OTHER THAN FUCKING FAKE NOSTALGIA COMPARED TO 2003PAGE AND TWTACCT (and even blockpage).

FUCKING WAKE UP YOU MESSENGERGEEK KIDS. FUCKING WAKE UP.

@forkiesassds just fix the fucking shit (https://github.com/JarTeam/retrosite/commit/0c0132a07f68f2774b7ece35c3e4530f15a492f7) please they hate me and will ignore me because of 2003page.

I'm not surpised if Retrosite mysteriously shuts down in early-2021 because the Fucknom domain expires, or they just renew that fucking .ga domain (it's .ga because 2003page's domain was a .ga domain until last month, which was because my previous website from late-2016/early-2017 was a .ga domain, which was because bob pony's site's domain used to be bobpony.ga, which might have been because of the word "gay")

**Comment by forkiesassds** [comment]
they took away my contributor

**Comment by PF94** [comment]
fuck retrosite

2003page and twtacct > retrosite
