### ISSUE TITLE
IE2 in NT 4.0 doesnt support Retrosite+Guestbook fails to load

### ISSUE THREAD

**Issue by LeoKids** [JarTeam/retrosite#21]
When i try to access it,It gets a github error,No matter what it takes,I had to install IE4 for that.

And when i access the guestbook it fails to load.

**Comment by JarHead4** [comment]
IE 2 was made in 1995, it's no surprise that it doesn't work with the site or guestbook PHP

Unless there's an issue outside of "*insert browser here* doesn't load the site", please refrain from creating an issue.
