### ISSUE TITLE
Remove all _vti_cnf folders

### ISSUE THREAD

**Issue by forkiesassds** [JarTeam/retrosite#5]
~~Mission impossible~~

**Comment by JarHead4** [comment]
Frontpage creates them automatically. We can't really delete them

**Comment by forkiesassds** [comment]
> Frontpage creates them automatically. We can't really delete them

Have you heard of .gitignore?

**Comment by JarHead4** [comment]
does it really matter if they're there or not? the site works fine.

**Comment by PF94** [comment]
``_vti_cnf`` fucked the source code of 2003page back when it was brand-new (around May 5th 2019/May 6th 2019), had to reset the whole project for that, but nothing was really lost (it was before the concept of "subsites" [websites inside a website, so a webring basically] was even implemented to 2003page.)
