### ISSUE TITLE
Joining. AGAIN

### ISSUE THREAD

**Issue by shadowdree** [JarTeam/retrosite#7]
Hoi, due to the shutdown of 2003page. FUCK CRAPPA! i'll join retrosite

[vriska folder.zip](https://github.com/JarTeam/retrosite/files/4602978/vriska.folder.zip)
here's my veteran folder

**Comment by shadowdree** [comment]
i mean this one
[Uploading vriska folder.zip…]()

**Comment by shadowdree** [comment]
[vriska folder.zip](https://github.com/JarTeam/retrosite/files/4603351/vriska.folder.zip)
i mean this one

**Comment by forkiesassds** [comment]
Could you join our discord server? https://discord.gg/qHGzKme

**Comment by shadowdree** [comment]
i don't wanna use discord. i'm underage

**Comment by forkiesassds** [comment]
Could you just go to https://github.com/JarTeam/retrosite/invitations

**Comment by shadowdree** [comment]
yes.

**Comment by shadowdree** [comment]
well i joined
