### ISSUE TITLE
Move 2003page Forever to another repository

### ISSUE THREAD

**Issue by PF94** [JarTeam/retrosite#8]
I've noticed your codefactor has now been a D+, and not an A. I've checked the site and i noticed it was because of 2003page forever. so just move it.

**Comment by forkiesassds** [comment]
Done.

**Comment by PF94** [comment]
hmm, for some reason i was expecting the "forever" source code to be transfered to 2003tech (because 2003page is 2003tech/Merengue Studios "property"), but it's still on jarteam...
